# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: biyi
    profiles:
        active:
            - dev
            - swagger
            - enc
    jackson:
        serialization.write_dates_as_timestamps: false   
    mvc:
        favicon:
            enabled: false      
                  
management:
    endpoints:
        web:
            #监控接口
            exposure:
                include: "info,health,prometheus"

ctsi:
    swagger:
        default-include-pattern: /api/.*
        title: ctsi API
        description: ctsi API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url: 
