# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
logging: 
   #日志级别
   level: 
      ROOT: DEBUG
spring:
   #激活一个或多个配置
   profiles:
      active:
         - dev
      include:
         - swagger
   jackson: 
      #格式化输出
      serialization.indent_output: true
      #时区
      time-zone: GMT+8
   jpa:
      hibername:
         #使用@Entity时，控制表结构生成行为，none是什么都不做
         ddl-auto: none
            #数据库开关
   liquibase:
      #数据库初始化开关
      enabled: true
      #初始化脚本路径
      change-log: classpath:/db/changelog/master.xml
   #数据源
   datasource:
            #数据库驱动
      driverClassName: com.mysql.cj.jdbc.Driver
      #数据库连接
      url: jdbc:mysql://localhost:3306/lecturersystem?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
            #数据库连接池
      type: com.zaxxer.hikari.HikariDataSource
      #数据库用户名
      username: root
      #数据库密码
      password: ENC(wuZFcESHQ9sVJl+hrZq3Bw==)
      hikari: 
         #最大连接池数
         maximumPoolSize: 20
      #是否自定义配置
      cachePrepStmts: true
      #连接池大小
      prepStmtCacheSize: 250
      #单条语句最大长度
      prepStmtCacheSqlLimit: 2048
      #新版本MySQL支持服务器端准备，是否开启
      useServerPrepStmts: true
   #国际化
   messages: 
      #配置路径
      basename: i18n/messages
      #字符集
      encoding: UTF-8
server:
   #端口号
   port: 9000
ctsi:
   # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
   cors: 
      #允许源 默认为允许所有，可以根据实际情况设置源
      allowedOriginPatterns: "*"
      #允许的HTTP方法
      allowed-methods: "*"
      #允许的字段
      allowed-headers: "*"
      #可从请求头中获取的字段
      exposed-headers: "Authorization,Link,X-Total-Count,Content-Disposition"
      #允许发送处理COOKIE
      allow-credentials: true
      #缓存时间
      max-age: 1800
   #允许跨域，多个以逗号分隔
   corspaths: "/api/**"
   #新增用户默认密码
   login-password: ctsi1234
   log: 
      #是否启用操作日志
      operation-log: 
         enable: false
      #是否启用登录日志
      login-log: 
         enable: false
   security: 
      authentication: 
         jwt:
            #token主题
            subject: testing
            #发行人信息
            issuer: secure.istio.io
            # token 加密算法 SHA256(默认)、HS512
            signature-algorithm: HS512
            #token key密钥
            secret: my-secret-token-to-change-in-production
            #token失效时间，秒
            token-validity-in-seconds: 86400
            #rememberme token失效时间
            token-validity-in-seconds-for-remember-me: 2592000
            #HS512算法加密token时的私钥
            private-key: '-----BEGIN RSA PRIVATE KEY-----MIIEpAIBAAKCAQEAt1cKkQqPh8iOv5BhKh7Rx6A2+1ldpO/jczML/0GBKu4X+lHrY8YbJrt29jyAXlWM8vHC7tXsqgUG+WziRD0D8nhnh10XC14SeH+3mVuBqph+TqhXTWsh9gtAIbeUHJjEI4I79QK4/wquPHHIGZBQDQQnuMh6vAS3VaUYJdEIoKvUBnAyY35kJZgyJSbrxLsEExL2zujUD/OY+/In2bq/3rFtDGNlgHyC7Gu2zXSXvfOA4O5m9BBXOc7eEqj7PoOKNaTxLN3YcuRtgR6NIXL4KLb6oyvIzoeiprt4+9q7sc3Dnkc5EV9kwWlEW2DHzhP6VYca0WXIIXc53U1AM3ewxwIDAQABAoIBABIKhaaqJF+XM7zUB0uuxrPfJynqrFVbqcUfQ9H1bzF7Rm7CeuhRiUBxeA5Y+8TMpFcPxT/dWzGL1xjaRxWx715/zKg8V9Uth6HF55o2r/bKlLtGw3iBz1C34LKwrul1eu+HlEDS6MNoGKcoBynE0qvFOedsCu/Pgv7xhQPLow60Ty1uM0AhbcPgi6yJ5ksRB1XjtEnW0t+c8yQSnU3mU8k230SdMhf4Ifud/5TPLjmXdFpyPi9uYiVdJ5oWsmMWEvekXoBnHWDDF/eTVkVMiTBorT4qn+Ax1VjHL2VOMO5ZbXEcpbIc3Uer7eZAaDQ0NPZK37IkIn9TiZ21cqzgbCkCgYEA5enHZbD5JgfwSNWCaiNrcBhYjpCtvfbT82yGW+J4/Qe/H+bY/hmJRRTKf0kVPdRwZzq7GphVMWIuezbOk0aFGhk/SzIveW8QpLY0FV/5xFnGNjV9AuNcxrmgVshUsyQvr1TFkbdkC6yuvNgQfXfnbEoaPsXYEMCii2zqdF5lWGUCgYEAzCR26g8vEQx0hdRS5d0zD2/9IRYNzfP5oK0+F3KHH2OuwlmQVIo7IhCiUgqserXNBDefhj+GNcU8O/yXLomAXG7VG/cLWRrpY8d9bcRMrwb0/SkNr0yNrkqHiWQ/PvR+2MLkviWFZTTp8YizPA+8pSC/oFd1jkZF0UhKVAREM7sCgYB5+mfxyczFopyW58ADM7uCg0goixXCnTuiAEfgY+0wwXVjJYSme0HaxscQdOOyJA1ml0BBQeShCKgEcvVyKY3gZNixunR5hrVbzdcgKAVJaR/CDuq+J4ZHYKByqmJVkLND4EPZpWSM1Rb31eIZzw2W5FG8UBbr/GfAdQ6GorY+CQKBgQCzWQHkBmz6VG/2t6AQ9LIMSP4hWEfOfh78q9dWMDdIO4JomtkzfLIQ7n49B8WalShGITwUbLDTgrG1neeQahsMmg6+X99nbD5JfBTVH9WjG8CWvb+ZF++NhUroSNtLyu+6LhdaeopkbQVvPwMArG62wDu6ebv8v/5MrG8ouwrUSwKBgQCxV43ZqTRnEuDlF7jMN+2JZWhpbrucTG5INoMPOC0ZVatePszZjYm8LrmqQZHer2nqtFpyslwgKMWgmVLJTH7sVf0hS9po0+iSYY/r8e/c85UdUreb0xyTx8whrOnMMODCAqu4W/Rx1Lgf2vXIx0pZmlt8Df9i2AVg/ePR6jO3Nw==-----END
                      RSA PRIVATE KEY-----'
            #HS512算法加密token时的公钥
            public-key: '-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt1cKkQqPh8iOv5BhKh7Rx6A2+1ldpO/jczML/0GBKu4X+lHrY8YbJrt29jyAXlWM8vHC7tXsqgUG+WziRD0D8nhnh10XC14SeH+3mVuBqph+TqhXTWsh9gtAIbeUHJjEI4I79QK4/wquPHHIGZBQDQQnuMh6vAS3VaUYJdEIoKvUBnAyY35kJZgyJSbrxLsEExL2zujUD/OY+/In2bq/3rFtDGNlgHyC7Gu2zXSXvfOA4O5m9BBXOc7eEqj7PoOKNaTxLN3YcuRtgR6NIXL4KLb6oyvIzoeiprt4+9q7sc3Dnkc5EV9kwWlEW2DHzhP6VYca0WXIIXc53U1AM3ewxwIDAQAB-----END
                      PUBLIC KEY-----'
         cas:
            casServerUrlPrefix: http://localhost:8080/cas
   token:
      #token内容: id,auth
      content: auth
      #token:存储位置 server、redis、
      storageMedia: server
   captcha: 
      #验证码KEY策略
      keyProvider: simpleCaptchaKeyProvider
      #验证码组件缓存实现，提供两种实现，redis和基于guava的缓存，redis支持集群部署，guava只支持单机使用。可选值：guavaCaptchaCache，redisCaptchaCache
      cache: guavaCaptchaCache
   password-check: 
      #密码过期时间，单位 月
      expire-months: 3
      #密码最小长度
      check-min-length: 8
      #密码最大长度
      check-max-length: 20
      #检查密码包含小写字母
      check-lowercase: true
      #检查密码包含大写字母
      check-uppercase: true
      #检查密码包含数字
      check-digit: true
      #检查密码包含键盘相邻字符
      check-keyboard: true
      #检查密码包含特殊字符
      check-special-character: true
   login: 
      #密码输错达到次数，锁定用户
      bad-password-attempts: 5
      #锁定时间，单位s
      lockout-time: 3600
      #记录密码错误缓存实现，提供两种实现，redis和基于guava的缓存，redis支持集群部署，guava只支持单机使用。可选值：guavaLoginCache，redisLoginCache
      cache: guavaLoginCache
   #统计认证组件路径配置
   component-statics: 
      #日志存放路径
      log-path: /log
      #证书路径
      cert-path: classpath:/license.lc
   #密码加密私钥  请生成模板工程后立即修改
   RSA-prikey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALQmvU3NVRAxu6uRlPpGS3R5o+YfxM3oTbnyXa1kwmBUI/+wvigqOugpiY08GRJKIsoWv3DAmp96wx55/oKEZFReMboNfSjFBF7R/n9SfISb82JwnDP3HCRTfiBu6jVUH8QDZBnl2XWuP2JKyKoosrr9AWVW7OyVF0BdhkLv2+mvAgMBAAECgYA3q3D8ReNvaa7wycAbxvUyPRSk3FRYvNyoBXllR6m5Usb9EITyrHofnBZhipzExhwSDw2BrkMZ3TnGhTRc6MSHuQAnkI8g1yB/UJRLX752M+m/MBEm/xNEK4D1z1yIueGv8zxjKVdNw8o8WGJV0V2FMKWLWW/r6PfcUTGERQNIQQJBANv9O2q0cEB7lujyuYvFVTKzG6d+msrzSqZ6yNWQSqVfGy5W2KE39Bg9Iklg0nWg0hWjO+Kn+wQ2BuidlpXn+ykCQQDRpBRx2w6y7yPR8ZThpHPK8HL0ZKarf7oW7ZViAXspL3hhnMXSeq9oTMctdm1riCTlAeJ6Cu5Rk/K0sjLRFbEXAkEAooCGEoVlYgypZjxeWWQUUlZB+FEqUP60xxNuJWvn6A7AClP2w+iMNBd8q02NSXzZk0g4JW7Gms65/bzjDqsFOQJAUFqz+3AbkjpXYIFYr6R5PbAsX8C0ocezbFZki8xFiOPJIKEWsjaURUYokiRyjGUCv0SZqm3GKz6qKNik4b+OwQJAfynVAyHawEWB7laoDiKMk4rtX55TQdtzqmIlfI63wMCmtAByOauQp6YiUzht6I73C/wBQ7o49ys0RTU0LyDQuQ==
#mybatis配置
mybatis: 
   configLocation: classpath:/mybatis-config.xml
pagehelper:
   #分页设置
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   pageSizeZero: true
management:
   health: 
      redis: 
         #关闭REDIS健康检查
         enabled: false
      elasticsearch: 
         #关闭ES健康检查
         enabled: false
